### ISSUE TITLE
Indicator Mapping

### ISSUE THREAD

**Issue by l-gorman** [RHoMIS/rhomis-R-package#23]
# Indicator Dictionary

Produce a dictionary of the different indicators included in the core dataset. Add what column's are needed to calculate these indicators. And also add which columns these indicators depend on. Add the units which are needed for these indicators, and whether these unit conversions exist also.

**Comment by ekuw** [comment]
Once we have a strategy for flagging which indicators need to be calculated based on the data we need to remove the construction of dummy conversion tables (e.g. [here](https://github.com/l-gorman/rhomis-R-package/blob/1e552a4d38b46994b445dc57127851a44d75bd77/R/UnitsAndConversions.R#L384)) since this is probably never going to be the correct thing to do. We should bail out with a warning instead.

**Comment by l-gorman** [comment]
Yes agree with this. If the conversion table does not exist, then the calculations should not proceed. Is that what you're saying?

**Comment by ekuw** [comment]
Yes exactly.
